crud/urls.py
from django.urls import path

from .views import index,about,create,contacts,partData,deleteBlog,updateBlog

app_name="crud"
urlpatterns = [
    path("",index,name="home"),
    path("about/",about,name="about"),
    path("create/",create,name="create"),
    path("<int:id>/",partData,name="particular"),
    path("contacts/",contacts,name="contacts"),
    path("delete/<int:id>/",deleteBlog,name="deleteblog"),
    path("update/<int:id>/",updateBlog,name="updateblog")


   
    
]

projectdemo/urls.py
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('backend/', admin.site.urls),
    path("",include("crud.urls")),
    path("users/",include("users.urls"))
    
]

users/urls.py
from django.urls import path,include

from .views import registerUser,loginUser,logoutUser


app_name="users"
urlpatterns = [
    path("register/",registerUser,name="signup"),
    path("login/",loginUser,name="signin"),
    path("logout/",logoutUser,name="signout"),
  
    
]

crud/models.py
from django.db import models
from django.contrib.auth.models import User



class Blog(models.Model):
    title = models.CharField(max_length=200)
    subheading = models.CharField(max_length=200,default="This is subheading")
    description=models.TextField() 
    user = models.ForeignKey(User,on_delete=models.CASCADE)   

    def __str__(self):
        return self.title


class Contacts(models.Model):
    
    name = models.CharField(max_length=150)
    email=models.EmailField()


    def __str__(self):
        return self.name

users/models.py
from django.db import models

# Create your models here.

crud/forms.py
from django import forms

from .models import Blog



class BlogForm(forms.ModelForm):
    class Meta:
        model=Blog
        fields="__all__"

crud/views.py
from django.shortcuts import render,redirect
from .models import Blog,Contacts # manager objects
from .forms import BlogForm
from django.core.paginator import Paginator
from projectdemo.settings import EMAIL_HOST_USER #replace root with your project name
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required




# Create your views here.
def index(request):
    blog = Blog.objects.all()
    paginator = Paginator(blog,2)
    pages = request.GET.get('page')
    page_obj = paginator.get_page(pages)
    if(request.method == "POST"):
        searchData = request.POST.get("search")
        if(searchData != ""):
            data = Blog.objects.filter(title__icontains=searchData)
            return render(request,"crud/home.html",{'blogs':data})      
    return render(request,"crud/home.html",{"blogs":page_obj})


def about(request):
    return render(request,"crud/about.html")

@login_required
def create(request):
    form = BlogForm(request.POST or None)
  
    if form.is_valid():        
        form.save()
        return  redirect("crud:home")
    return render(request,"crud/createblog.html",{"form":form})

def deleteBlog(request,id):
    blog = Blog.objects.get(id=id)
    blog.delete()
    return redirect("crud:home")

def updateBlog(request,id):
    blog = Blog.objects.get(id=id)
    form = BlogForm(request.POST or None,instance=blog)
    if (form.is_valid()):
        form.save()
        return redirect("crud:home")
    context = {
        "form":form,
        "title":blog.title,
        "subheading":blog.subheading,
        "description":blog.description
    }
    return render(request,"crud/createblog.html",context)
    

def partData(request,id):
    blog = Blog.objects.get(id=id)
    print(blog)
    context = {
        "blog":blog
    }
    return render(request,"crud/particular.html",context)

def contacts(request):
    
    if(request.method == "POST"):
        dataName = request.POST.get("name")
        dataEmail = request.POST.get("email")
        dataMessage = request.POST.get("message")
        subject = "Wants to collaborate!!!"
        recipient = "heraldcollege@yopmail.com","np03cs4s220226@heraldcollege.edu.np",
        html_content = render_to_string('crud/email.html',{'name':dataName,'description':dataMessage,'mail':dataEmail})
        email=EmailMessage(
            subject,
            html_content,
            EMAIL_HOST_USER,
            recipient
        )
        email.fail_silently=False
        if email!=None:
            email.send()

       

        contacts = Contacts(
            name=dataName,
            email=dataEmail
        )

        contacts.save()
        print(dataName,dataEmail,dataMessage)
        # return redirect("crud:home")
      
           

    return render(request,"crud/contact.html")

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import logout,authenticate,login
from django.contrib.auth.decorators import login_required

# Create your views here.
def registerUser(request):
    if request.method== "POST":
        username = request.POST.get("username")
        email = request.POST.get("email")
        firstname = request.POST.get("firstname")
        lastname = request.POST.get("lastname")
        password = request.POST.get("password")
        confirmpassword = request.POST.get("confirmpassword")
        if password == confirmpassword:
            user = User.objects.create_user(
                username=username,
                email=email,
                first_name=firstname,
                last_name=lastname,
                password=password
            )
            user.save()
            return redirect("crud:home")
        else:
            print("password validation failed")
        

    return render(request,"users/register.html")

def loginUser(request):
    if(request.user.is_authenticated):
        return redirect("crud:home")
    else:

        print(request.user)
        if request.method == "POST":
            username=request.POST.get("username")
            password=request.POST.get("password")
            
            user=authenticate(request,username=username,password=password)
            if user is not None:
                login(request,user)
                return redirect("crud:home")
            else:
                print("User Validation Failed - 401")
                return redirect("users:signin")
        return render(request,"users/login.html")

@login_required
def logoutUser(request):
    logout(request)
    return redirect("crud:home")

crud/templates/crud/about.html
{%extends 'base.html'%}
{%load static%}
{%block body%}
<!-- Page Header-->
<header class="masthead" style="background-image: url({%static 'assets/img/about-bg.jpg' %})">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="page-heading">
                    <h1>About Me</h1>
                    <span class="subheading">This is what I do.</span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content-->
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
            </div>
        </div>
    </div>
</main>

{%endblock%}

crud/templates/crud/contact.html
{%extends 'base.html'%}
{%load static%}

{%block body%}
<!-- Page Header-->
<header class="masthead" style="background-image: url({%static 'assets/img/contact-bg.jpg' %})">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="page-heading">
                    <h1>Contact Me</h1>
                    <span class="subheading">Have questions? I have answers.</span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content-->
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
                <div class="my-5">
                    
                    <form method="post">
                        {%csrf_token%}
                        <div class="form-floating">
                            <input class="form-control" id="name" type="text" name="name"  required placeholder="Enter your name..."  />
                            <label for="name">Name</label>
                            <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                        </div>
                        <div class="form-floating">
                            <input class="form-control" id="email" type="email" name="email" required placeholder="Enter your email..." />
                            <label for="email">Email address</label>
                            <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
                            <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
                        </div>
                       
                        <div class="form-floating">
                            <textarea class="form-control" id="message" required name="message" placeholder="Enter your message here..." style="height: 12rem" data-sb-validations="required"></textarea>
                            <label for="message">Message</label>
                            <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.</div>
                        </div>
                        <br />
                        
                    
                        <button class="btn btn-primary text-uppercases" id="submitButton" type="submit">Send</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
{%endblock%}

crud/templates/crud/contactus.html
<div class="container">

    <form  method="post">
        {%csrf_token%}
        <p>Name</p>
    <input type="text" name="name" required autofocus/>

    <p>email</p>
    <input type="emil" name="email" required/>
    <button type="submit">Send</button>
    </form>


    
</div>

crud/templates/crud/create.html
<div>
    <form  method="post">
        {%csrf_token%}
        {{form}}
        <button type="submit">save</button>
    </form>
</div>

crud/templates/crud/createblog.html
{%extends 'base.html'%}
{%load static%}

{%block body%}
<!-- Page Header-->
<header class="masthead" style="background-image: url({%static 'assets/img/contact-bg.jpg' %})">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="page-heading">
                    <h1>Create Blog</h1>
                    <span class="subheading">Let's create the blog.</span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content-->
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                
                <div class="my-5">
               
                    <form id="contactForm" method="post">
                        {%csrf_token%}
                        <div class="form-floating">

                            <input class="form-control" id="id_title" for="id_title" name="title" type="text" value="{{title}}" placeholder="Enter your name..."  autofocus data-sb-validations="required" />
                            <label for="id_title">Title</label>
                            <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                        </div>
                        <div class="form-floating">
                            <input class="form-control" id="id_subheading" for="id_subheading" name="subheading" type="text" value="{{subheading}}" placeholder="Enter your email..." data-sb-validations="required,email" />
                            <label for="id_subheading">SubHeading</label>
                            <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
                            <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
                        </div>
                     
                        <div class="form-floating">
                            <textarea class="form-control" id="id_description" for="id_description" name="description" placeholder="Enter your message here..." style="height: 12rem" data-sb-validations="required">{{description}}</textarea>
                            <label for="id_description">Description</label>
                            <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.</div>
                        </div>


                                             
                        <input type="hidden" name="user" value="{{user.id}}"/>
                        
                       
                       
                        <!-- Submit Button-->
                        <button class="btn btn-primary text-uppercase " id="submitButton" type="submit">Send</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
{%endblock%}

crud/templates/crud/email.html
Hello, Rukesh 

You got mail from {{name}}.

{{description}}

Therefore, if you want to contact him. His/Her email address is {{mail}}.

--
Best Regards,
{{name}}
    

crud/templates/crud/home.html
{%extends 'base.html'%}
{% load static %}



{%block body%}
<!-- Page Header-->
<header class="masthead" style="background-image: url({%static 'assets/img/home-bg.jpg' %})">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Clean Blog</h1>
                    <span class="subheading">A Blog Theme by Start Bootstrap</span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content-->


    <div class="container">
      <form class="d-flex" role="search" method="post">
        {%csrf_token%}
        <input class="form-control me-2" name="search" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>


<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">



            {%for blog in blogs%}
                 <!-- Post preview-->
            <div class="post-preview">
                <a href="{%url 'crud:particular' blog.id%}">
                    <h2 class="post-title">{{blog.title}}</h2>
                    <h3 class="post-subtitle">{{blog.subheading}}</h3>
                </a>
                <p class="post-meta">
                    Posted by
                    <a href="#!">{{blog.user}}</a>
                    on September 24, 2023
                </p>
            </div>
            
           
            <!-- Divider-->
            <hr class="my-4" />

            {%endfor%}

             <!-- Paginator -->    
    <div class="pagination">
        <span class="step-links">
            {% if blogs.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ blogs.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ blogs.number }} of {{ blogs.paginator.num_pages }}.
            </span>
    
            {% if blogs.has_next %}
                <a href="?page={{ blogs.next_page_number }}">next</a>
                <a href="?page={{ blogs.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    <br>
           
            
           
        </div>

        






    </div>


   



</div>








{%endblock%}

crud/templates/crud/index.html
<!-- Home all blogs -->
{%for blog in blogs%}
<a href="{%url 'particular' blog.id%}">

    <h1>{{blog.title}}</h1>
</a>

<h5>{{blog.description}}</h5>

{%endfor%}


<!-- Particuar Blog -->
{%if blog%}
<h1>{{blog.title}}</h1>
<h5>{{blog.description}}</h5>

<a href="{%url 'crud:deleteblog' blog.id%}" type="submit">Delete</a>
<a href="{%url 'crud:updateblog' blog.id%}" type="Update">Update</a>

{%endif%}

crud/templates/crud/particular.html
{%extends 'base.html'%}
{% load static %}



{%block body%}
<!-- Page Header-->
{%if blog%}
<header class="masthead" style="background-image: url({%static 'assets/img/post-bg.jpg' %})">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="post-heading">
                    <h1>{{blog.title}}</h1>
                    <h2 class="subheading">{{blog.subheading}}</h2>
                    <span class="meta">
                        Posted by
                        <a href="#!">Start Bootstrap</a>
                        on August 24, 2023
                    </span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Post Content-->
<article class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                {{blog.description}}

                <div class="container">
                    <a href="{%url 'crud:deleteblog' blog.id%}">
                        <button class="btn btn-danger" type="submit">Delete</button>
                    </a>
                    <a href="{%url 'crud:updateblog' blog.id%}">
                        <button class="btn btn-info" type="submit">Update</button>
                    </a>
                   </div>
            </div>
           
           
        </div>
       
        
    </div>
</article>
<!-- Main Content-->


         
{%endif%}



{%endblock%}

crud/templates/crud/post.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/post-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="post-heading">
                            <h1>Man must explore, and this is exploration at its greatest</h1>
                            <h2 class="subheading">Problems look mighty small from 150 miles up</h2>
                            <span class="meta">
                                Posted by
                                <a href="#!">Start Bootstrap</a>
                                on August 24, 2023
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Post Content-->
        <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Never in all their history have men been able truly to conceive of the world as one: a single sphere, a globe, having the qualities of a globe, a round earth in which all the directions eventually meet, in which there is no center because every point, or none, is center — an equal earth which all men occupy as equals. The airman's earth, if free men make it, will be truly round: a globe in practice, not in theory.</p>
                        <p>Science cuts two ways, of course; its products can be used for both good and evil. But there's no turning back from science. The early warnings about technological dangers also come from science.</p>
                        <p>What was most significant about the lunar voyage was not that man set foot on the Moon but that they set eye on the earth.</p>
                        <p>A Chinese tale tells of some men sent to harm a young girl who, upon seeing her beauty, become her protectors rather than her violators. That's how I felt seeing the Earth for the first time. I could not help but love and cherish her.</p>
                        <p>For those who have seen the Earth from space, and for the hundreds and perhaps thousands more who will, the experience most certainly changes your perspective. The things that we share in our world are far more valuable than those which divide us.</p>
                        <h2 class="section-heading">The Final Frontier</h2>
                        <p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>
                        <p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>
                        <blockquote class="blockquote">The dreams of yesterday are the hopes of today and the reality of tomorrow. Science has not yet mastered prophecy. We predict too much for the next year and yet far too little for the next ten.</blockquote>
                        <p>Spaceflights cannot be stopped. This is not the work of any one man or even a group of men. It is a historical process which mankind is carrying out in accordance with the natural laws of human development.</p>
                        <h2 class="section-heading">Reaching for the Stars</h2>
                        <p>As we got further and further away, it [the Earth] diminished in size. Finally it shrank to the size of a marble, the most beautiful you can imagine. That beautiful, warm, living object looked so fragile, so delicate, that if you touched it with a finger it would crumble and fall apart. Seeing this has to change a man.</p>
                        <a href="#!"><img class="img-fluid" src="assets/img/post-sample-image.jpg" alt="..." /></a>
                        <span class="caption text-muted">To go places and do things that have never been done before – that’s what living is all about.</span>
                        <p>Space, the final frontier. These are the voyages of the Starship Enterprise. Its five-year mission: to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no man has gone before.</p>
                        <p>As I stand out here in the wonders of the unknown at Hadley, I sort of realize there’s a fundamental truth to our nature, Man must explore, and this is exploration at its greatest.</p>
                        <p>
                            Placeholder text by
                            <a href="http://spaceipsum.com/">Space Ipsum</a>
                            &middot; Images by
                            <a href="https://www.flickr.com/photos/nasacommons/">NASA on The Commons</a>
                        </p>
                    </div>
                </div>
            </div>
        </article>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

projectdemo/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{%url 'crud:home'%}">Mero Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto py-4 py-lg-0">
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{%url 'crud:home'%}">Home</a></li>
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{%url 'crud:create'%}">Create</a></li>
                
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{%url 'crud:about'%}">About</a></li>
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{%url 'users:signup'%}">Sign Up</a></li>
                
                {%if not user.is_authenticated%}
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{%url 'users:signin'%}">Sign In</a></li>
                {%endif%}
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{%url 'crud:contacts'%}">Contact</a></li>
                {%if user.is_authenticated%}
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{%url 'users:signout'%}">Sign Out</a></li>
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="#">Welcome, {{user}}</a></li>
                {%endif%}

                
                

            </ul>
        </div>
    </div>
</nav>